# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncrementalYearId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('number', models.PositiveIntegerField()),
                ('value', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='incrementalyearid',
            unique_together=set([('year', 'number')]),
        ),
    ]
