# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-04 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incrementalyearid',
            name='organisation',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='incrementalyearid',
            unique_together=set([('year', 'number', 'organisation')]),
        ),
    ]
