# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='naam')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='omschrijving')),
            ],
            options={
                'verbose_name': 'applicatie',
                'verbose_name_plural': 'applicaties',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ApplicationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='naam')),
            ],
            options={
                'verbose_name': 'applicatie groep',
                'verbose_name_plural': 'applicatie groepen',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('beantwoordVraag', 'beantwoordVraag'), ('OntvangAsynchroon', 'OntvangAsynchroon'), ('VerwerkSynchroonVrijBericht', 'VerwerkSynchroonVrijBericht')], max_length=50, verbose_name='type')),
                ('url', models.CharField(max_length=250, verbose_name='url')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiauth.Application')),
            ],
            options={
                'verbose_name': 'endpoint',
                'verbose_name_plural': 'endpoints',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='naam')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='omschrijving')),
            ],
            options={
                'verbose_name': 'organisatie',
                'verbose_name_plural': 'organisaties',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ServiceOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='naam')),
                ('namespace', models.CharField(max_length=250, verbose_name='namespace')),
                ('operation_name', models.CharField(max_length=150, unique=True, verbose_name='functienaam')),
            ],
            options={
                'verbose_name': 'service functie',
                'verbose_name_plural': 'service functies',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='applicationgroup',
            name='service_operations',
            field=models.ManyToManyField(to='apiauth.ServiceOperation', verbose_name='service functies'),
        ),
        migrations.AddField(
            model_name='application',
            name='groups',
            field=models.ManyToManyField(blank=True, to='apiauth.ApplicationGroup', verbose_name='groepen'),
        ),
        migrations.AddField(
            model_name='application',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiauth.Organisation', verbose_name='organisatie'),
        ),
    ]
