# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-15 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import zaakmagazijn.rgbz.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rgbz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerelateerdeexternezaak',
            name='verantwoordelijke_organisatie',
            field=models.CharField(help_text='Het RSIN van de organisatie die verantwoordelijk is voor de behandeling van de gerelateerde ZAAK.', max_length=9, validators=[zaakmagazijn.rgbz.validators.validate_non_negative_string]),
        ),
        migrations.AlterField(
            model_name='informatieobject',
            name='bronorganisatie',
            field=models.CharField(blank=True, help_text='Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die het informatieobject heeft gecreëerd of heeft ontvangen en als eerste in een samenwerkingsketen heeft vastgelegd.', max_length=9, null=True, validators=[zaakmagazijn.rgbz.validators.validate_non_negative_string]),
        ),
        migrations.AlterField(
            model_name='ingezeteneobject',
            name='burgerservicenummer',
            field=models.CharField(help_text='Het burgerservicenummer, bedoeld in artikel 1.1 van de Wet algemene bepalingen burgerservicenummer.', max_length=9, validators=[zaakmagazijn.rgbz.validators.validate_non_negative_string]),
        ),
        migrations.AlterField(
            model_name='natuurlijkpersoon',
            name='burgerservicenummer',
            field=models.CharField(help_text='Het burgerservicenummer, bedoeld in artikel 1.1 van de Wet algemene bepalingen burgerservicenummer.', max_length=9, validators=[zaakmagazijn.rgbz.validators.validate_non_negative_string]),
        ),
        migrations.AlterField(
            model_name='natuurlijkpersoon',
            name='faxnummer',
            field=models.CharField(blank=True, help_text='Faxnummer waaronder het subject in de regel bereikbaar is.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nietingezeteneobject',
            name='burgerservicenummer',
            field=models.CharField(help_text='Het burgerservicenummer, bedoeld in artikel 1.1 van de Wet algemene bepalingen burgerservicenummer.', max_length=9, validators=[zaakmagazijn.rgbz.validators.validate_non_negative_string]),
        ),
        migrations.AlterField(
            model_name='nietnatuurlijkpersoon',
            name='faxnummer',
            field=models.CharField(blank=True, help_text='Faxnummer waaronder het subject in de regel bereikbaar is.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='organisatorischeeenheid',
            name='faxnummer',
            field=models.CharField(blank=True, help_text='Faxnummer waaronder het subject in de regel bereikbaar is.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vestiging',
            name='faxnummer',
            field=models.CharField(blank=True, help_text='Faxnummer waaronder het subject in de regel bereikbaar is.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zaak',
            name='archiefstatus',
            field=models.CharField(choices=[('Nog te archiveren', 'Nog te archiveren'), ('Gearchiveerd', 'Gearchiveerd'), ('Vernietigd', 'Vernietigd'), ('Overgedragen', 'Overgedragen')], help_text='De fase waarin het zaakdossier zich qua archivering bevindt', max_length=20),
        ),
        migrations.AlterField(
            model_name='zaak',
            name='bronorganisatie',
            field=models.CharField(help_text='Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die de zaak heeft gecreeerd.', max_length=9, validators=[zaakmagazijn.rgbz.validators.validate_non_negative_string]),
        ),
        migrations.AlterField(
            model_name='zaak',
            name='verantwoordelijke_organisatie',
            field=models.CharField(help_text='Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die eindverantwoordelijk is voor de behandeling van de zaak.', max_length=9, validators=[zaakmagazijn.rgbz.validators.validate_non_negative_string]),
        ),
    ]
