# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-20 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgbz', '0002_auto_20170915_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naam',
            name='adelijke_titel',
            field=models.CharField(blank=True, choices=[('B', 'Baron'), ('B', 'Barones'), ('G', 'Graaf'), ('G', 'Gravin'), ('H', 'Hertog'), ('H', 'Hertogin'), ('M', 'Markies'), ('M', 'Markiezin'), ('P', 'Prins'), ('P', 'Prinses'), ('R', 'Ridder')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='naam',
            name='voornamen',
            field=models.CharField(blank=True, help_text='Voornamen bij de naam die de persoon wenst te voeren.', max_length=200, null=True),
        ),
    ]
