# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-13 14:36
from __future__ import unicode_literals

from django.db import migrations, models

import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rgbz', '0005_auto_20171123_1005'),
    ]

    # This is quite a destructive migration but it has been impossible to
    # create via OrganisatorischeEenheden services.
    operations = [
        migrations.RemoveField(
            model_name='organisatorischeeenheid',
            name='gevestigd_in',
        ),
        migrations.DeleteModel('VestigingVanZaakBehandelendeOrganisatie'),
        migrations.CreateModel(
            name='VestigingVanZaakBehandelendeOrganisatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='vestigingvanzaakbehandelendeorganisatie',
            name='is_specialisatie_van',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rgbz.Vestiging'),
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='gevestigd_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rgbz.VestigingVanZaakBehandelendeOrganisatie'),
        ),
    ]
