# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-13 14:36
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import F

import django.db.models.deletion


def oe_backup_forward(apps, schema_editor):
    OrganisatorischeEenheid = apps.get_model('rgbz.OrganisatorischeEenheid')
    OrganisatorischeEenheid.objects.all().update(
        gevestigd_in_old=F('gevestigd_in')
    )


def vzo_forward(apps, schema_editor):
    VestigingVanZaakBehandelendeOrganisatie = apps.get_model('rgbz.VestigingVanZaakBehandelendeOrganisatie')
    VestigingVanZaakBehandelendeOrganisatie.objects.all().update(
        id=F('is_specialisatie_van')
    )


def vzo_backward(apps, schema_editor):
    VestigingVanZaakBehandelendeOrganisatie = apps.get_model('rgbz.VestigingVanZaakBehandelendeOrganisatie')
    VestigingVanZaakBehandelendeOrganisatie.objects.all().update(
        is_specialisatie_van=F('id')
    )


def oe_restore_forward(apps, schema_editor):
    OrganisatorischeEenheid = apps.get_model('rgbz.OrganisatorischeEenheid')
    OrganisatorischeEenheid.objects.all().update(
        gevestigd_in=F('gevestigd_in_old')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('rgbz', '0005_auto_20171123_1005'),
    ]

    operations = [
        # Step 1: Backup related model FKs in IntegerField and delete it:
        # - rgbz.OrganisatorischeEenheid

        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='gevestigd_in_old',
            field=models.IntegerField(blank=True, null=True),
        ),

        migrations.RunPython(oe_backup_forward),

        migrations.RemoveField(
            model_name='organisatorischeeenheid',
            name='gevestigd_in',
        ),

        # Step 2: Adjust rgbz.VestigingVanZaakBehandelendeOrganisatie
        # - Rename old PK name to FK name
        # - Add future PK field as IntegerField
        # - Copy over the old PK values to the future PK field
        # - Alter the future PK field to an AutoField
        # - Alter the old PK field to an FK.

        migrations.RenameField(
            model_name='vestigingvanzaakbehandelendeorganisatie',
            old_name='vestiging_ptr',
            new_name='is_specialisatie_van',
        ),
        migrations.AddField(
            model_name='vestigingvanzaakbehandelendeorganisatie',
            name='id',
            field=models.IntegerField(blank=True, null=True),
        ),

        migrations.RunPython(vzo_forward, vzo_backward),

        migrations.AlterField(
            model_name='vestigingvanzaakbehandelendeorganisatie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vestigingvanzaakbehandelendeorganisatie',
            name='is_specialisatie_van',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rgbz.Vestiging'),
        ),

        # Step 3: Add the deleted field in step 1, but with null=True
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='gevestigd_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rgbz.VestigingVanZaakBehandelendeOrganisatie'),
            preserve_default=False,
        ),
    ]
