# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-23 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgbz', '0008_flatten_naam_groupattribute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Naam',
        ),
    ]
