# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 12:56
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F


def oe_restore_forward(apps, schema_editor):
    OrganisatorischeEenheid = apps.get_model('rgbz.OrganisatorischeEenheid')
    OrganisatorischeEenheid.objects.all().update(
        gevestigd_in=F('gevestigd_in_old')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('rgbz', '0009_delete_naam'),
    ]

    operations = [
        # Step 4 (new migration): Restore data
        # - Copy the backup field of step 1, into the new field from step 3.
        migrations.RunPython(oe_restore_forward),
    ]
