# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rgbz', '0010_restore-oe'),
    ]

    operations = [
        # Step 5 (new migration): Restore constraints and cleanup
        # - Remove the old field
        # - Don't allow null=True on the FK

        migrations.RemoveField(
            model_name='organisatorischeeenheid',
            name='gevestigd_in_old',
        ),
        migrations.AlterField(
            model_name='organisatorischeeenheid',
            name='gevestigd_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rgbz.VestigingVanZaakBehandelendeOrganisatie'),
        ),
    ]
