# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import zaakmagazijn.utils.fields
import zaakmagazijn.utils.stuf_datetime


class Migration(migrations.Migration):

    dependencies = [
        ('rgbz', '0011_cleanup-oe'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaakinformatieobject',
            name='begin_geldigheid',
            field=zaakmagazijn.utils.fields.StUFDateTimeField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='zaakinformatieobject',
            name='begin_relatie',
            field=zaakmagazijn.utils.fields.StUFDateTimeField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='zaakinformatieobject',
            name='eind_geldigheid',
            field=zaakmagazijn.utils.fields.StUFDateTimeField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='zaakinformatieobject',
            name='eind_relatie',
            field=zaakmagazijn.utils.fields.StUFDateTimeField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='zaakinformatieobject',
            name='tijdstip_registratie',
            field=zaakmagazijn.utils.fields.StUFDateTimeField(blank=True, default=zaakmagazijn.utils.stuf_datetime.now, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='rolomschrijving',
            field=models.CharField(choices=[('Adviseur', 'Adviseur'), ('Behandelaar', 'Behandelaar'), ('Belanghebbende', 'Belanghebbende'), ('Beslisser', 'Beslisser'), ('initiator', 'Initiator'), ('Klantcontacter', 'Klantcontacter'), ('Zaakcoordinator', 'Zaakcoordinator')], help_text='Algemeen gehanteerde benaming van de aard van de ROL', max_length=80),
        ),
        migrations.AlterField(
            model_name='rol',
            name='rolomschrijving_generiek',
            field=models.CharField(choices=[('Adviseur', 'Adviseur'), ('Behandelaar', 'Behandelaar'), ('Belanghebbende', 'Belanghebbende'), ('Beslisser', 'Beslisser'), ('initiator', 'Initiator'), ('Klantcontacter', 'Klantcontacter'), ('Zaakcoordinator', 'Zaakcoordinator'), ('Mede-initiator', 'Mede-initiator')], help_text='Algemeen gehanteerde benaming van de aard van de ROL', max_length=40),
        ),
    ]
