# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-20 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import zaakmagazijn.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rgbz', '0012_auto_20171222_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andernatuurlijkpersoonobject',
            name='geslachtsaanduiding',
            field=models.CharField(blank=True, choices=[('M', 'Man'), ('V', 'Vrouw'), ('O', 'Onbekend')], help_text='Een aanduiding die aangeeft of de persoon een man of een vrouw is, of dat het geslacht nog onbekend is.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='ingezeteneobject',
            name='geslachtsaanduiding',
            field=models.CharField(blank=True, choices=[('M', 'Man'), ('V', 'Vrouw'), ('O', 'Onbekend')], help_text='Een aanduiding die aangeeft of de persoon een man of een vrouw is, of dat het geslacht nog onbekend is.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='medewerker',
            name='geslachtsaanduiding',
            field=models.CharField(blank=True, choices=[('M', 'Man'), ('V', 'Vrouw'), ('O', 'Onbekend')], help_text='Een aanduiding die aangeeft of de persoon een man of een vrouw is, of dat het geslacht nog onbekend is.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='natuurlijkpersoon',
            name='geboortedatum_ingeschreven_persoon',
            field=zaakmagazijn.utils.fields.StUFDateField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='natuurlijkpersoon',
            name='geslachtsaanduiding',
            field=models.CharField(blank=True, choices=[('M', 'Man'), ('V', 'Vrouw'), ('O', 'Onbekend')], help_text='Een aanduiding die aangeeft of de persoon een man of een vrouw is, of dat het geslacht nog onbekend is.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='nietingezeteneobject',
            name='geslachtsaanduiding',
            field=models.CharField(blank=True, choices=[('M', 'Man'), ('V', 'Vrouw'), ('O', 'Onbekend')], help_text='Een aanduiding die aangeeft of de persoon een man of een vrouw is, of dat het geslacht nog onbekend is.', max_length=1, null=True),
        ),
    ]
