# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 14:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import zaakmagazijn.rgbz.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rgbz', '0015_auto_20180515_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerelateerdeexternezaak',
            name='zaakidentificatie',
            field=models.CharField(blank=True, db_index=True, help_text='De unieke identificatie van de gerelateerde ZAAK.', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='informatieobject',
            name='informatieobjectidentificatie',
            field=models.CharField(db_index=True, help_text='Een binnen een gegeven context ondubbelzinnige referentie naar het INFORMATIEOBJECT.', max_length=40, validators=[zaakmagazijn.rgbz.validators.AlphanumericExcludingDiacritic()]),
        ),
        migrations.AlterField(
            model_name='medewerker',
            name='medewerkeridentificatie',
            field=models.CharField(db_index=True, help_text='Een korte unieke aanduiding van de MEDEWERKER.', max_length=24),
        ),
        migrations.AlterField(
            model_name='object',
            name='identificatie',
            field=models.CharField(db_index=True, help_text='De unieke identificatie van het OBJECT', max_length=100),
        ),
        migrations.AlterField(
            model_name='organisatorischeeenheid',
            name='organisatieeenheididentificatie',
            field=models.CharField(db_index=True, help_text='Een korte identificatie van de organisatorische eenheid.', max_length=24),
        ),
        migrations.AlterField(
            model_name='organisatorischeeenheid',
            name='organisatieidentificatie',
            field=models.PositiveIntegerField(db_index=True, help_text='Het RSIN van de organisatie zijnde een Niet-natuurlijk persoon waarvan de ORGANISATORISCHE EENHEID deel uit maakt.'),
        ),
        migrations.AlterField(
            model_name='zaaktype',
            name='zaaktypeidentificatie',
            field=models.PositiveIntegerField(db_index=True, help_text='Unieke identificatie van het ZAAKTYPE binnen de CATALOGUS waarin het ZAAKTYPE voorkomt.', unique=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterUniqueTogether(
            name='statustype',
            unique_together=set([('zaaktype', 'statustypevolgnummer')]),
        ),
    ]
