# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-11 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgbz', '0016_auto_20180709_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='roltoelichting',
            field=models.CharField(db_index=True, max_length=1000),
        ),
    ]
